# Generated by Django 5.0.7 on 2024-08-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='creator',
        ),
        migrations.AddField(
            model_name='order',
            name='orderer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='cafe',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='creator_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
