# Generated by Django 5.0.7 on 2024-08-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_order', '0002_remove_order_user_remove_room_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='order',
            name='ice_hot',
        ),
        migrations.RemoveField(
            model_name='order',
            name='water_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='extra_options',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='temperature',
            field=models.CharField(choices=[('HOT', 'Hot'), ('ICE', 'Ice')], default='Unknown', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='ice_amount',
            field=models.CharField(choices=[('적게', '적게'), ('보통', '보통'), ('많이', '많이')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderer_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
